    """ This is the data type file in python. Not coded!
    """

class Application(object):
    def __init__(
        firstName="",
        middleName="",
        lastName="",
        biologicalSex="",
        ethnicity="",
        age=0,
        birthdate="",
        ssn="",
        countryOfBirth="",
        marriageStatus="",
        numberOfChildren=0,
        phone="",
        phonePart1="",
        phonePart2="",
        phonePart3="",
        address="",
        city="",
        state="",
        email="",
        informationProvider="",
        relationshipToPatient="",
        placeOfEmployment="",
        hasInsurance=False,
        primaryInsurance="",
        planType="",
        policyId="",
        policyHolder="",
        insuranceFromEmployer="",
        insuranceCompanyName="",
        groupNumberPlanCode="",
        hasDeductiblesOrCoPayments=False,
        deductibleAmount=0.0,
        copayment=0.0,
        employmentStatus="",
        currentEmployer="",
        positionTitle="",
        grossAnnualIncome=0.0,
        unemploymentPeriod="",
        receivesFinancialAssistance=False,
        assistanceExplanation="",
        receivesSocialSecurity=False,
        numberOfPeopleInHousehold=0,
        hasPhysician=False,
        physicianFirstName="",
        physicianLastName=""
    ):
        self.firstName: str=""
        self.middleName: str=""
        self.lastName: str=""
        self.biologicalSex: str=""
        self.ethnicity: str=""
        self.age: int=0
        self.birthdate: str=""
        self.ssn: str=""
        self.countryOfBirth: str=""
        self.marriageStatus: str=""
        self.numberOfChildren: int=0
        self.phone: str=""
        self.phonePart1: str=""
        self.phonePart2: str=""
        self.phonePart3: str=""
        self.address: str=""
        self.city: str=""
        self.state: str=""
        self.email: str=""
        self.informationProvider: str=""
        self.relationshipToPatient: str=""
        self.placeOfEmployment: str=""
        self.hasInsurance: bool=False
        self.primaryInsurance: str=""
        self.planType: str=""
        self.policyId: str=""
        self.policyHolder: str=""
        self.insuranceFromEmployer: str=""
        self.insuranceCompanyName: str=""
        self.groupNumberPlanCode: str=""
        self.hasDeductiblesOrCoPayments: bool=False
        self.deductibleAmount: float=0.0
        self.copayment: float=0.0
        self.employmentStatus: str=""
        self.currentEmployer: str=""
        self.positionTitle: str=""
        self.grossAnnualIncome: float=0.0
        self.unemploymentPeriod: str=""
        self.receivesFinancialAssistance: bool=False
        self.assistanceExplanation: str=""
        self.receivesSocialSecurity: bool=False
        self.numberOfPeopleInHousehold: int=0
        self.hasPhysician: bool=False
        self.physicianFirstName: str=""
        self.physicianLastName: str=""
        